### ISSUE TITLE
Default Selected Index Issue

### ISSUE THREAD

**Issue by cwestMobile** [GocePetrovski/ScrollableSegmentedControl#13]
So the only way I've been able to get the default selected index to actually highlight is by putting it in viewWillAppear, but I'd rather not do that. It is not working in viewDidLoad where I want it to.

Ideas?

**Comment by GocePetrovski** [comment]
This works just fine. See Demo project and try changing line 39 of `TableViewController.swift`
from `segmentedControl.selectedSegmentIndex = 0` to say `segmentedControl.selectedSegmentIndex = 2`
