### ISSUE TITLE
How to remove all segment items?

### ISSUE THREAD

**Issue by ibankstory** [GocePetrovski/ScrollableSegmentedControl#14]
I want to remove all segment items before change to new items

**Comment by binnilal** [comment]
Is there any methods to remove all segments?

**Comment by GocePetrovski** [comment]
No, there is no one method to remove all segments simply because it is trivial to write a for loop in order to achieve this. 

Closing, since this is not an issue but more of feature request.

**Comment by keegho** [comment]
I added it this way
`// MARK: - Managing Segments
    
    /**
     Removes all segments then call inserSegment() to add the new ones.
     */
    @objc public func removeAllSegments() {
        segmentsData.removeAll()
    }`
