### ISSUE TITLE
Can it implement custom width segments instead of fixed widths?

### ISSUE THREAD

**Issue by amberkatyal** [GocePetrovski/ScrollableSegmentedControl#16]
I have seen segment controls in apps having custom widths and underline bars animate according to their size. Where custom widths are determined by the contents in them. Here the height is fixed for the maximum width segment item or else the font size is reduced to fit in.
Hoping this could be implemented or have done already.

**Comment by abingeorgev** [comment]
@GocePetrovski https://github.com/GocePetrovski/ScrollableSegmentedControl/pull/17 will fix this.

**Comment by GocePetrovski** [comment]
This is coming soon. I'm having small issues with auto layout constraints when dynamically changing segmentStyle or fixedSegmentWidth properties.

**Comment by GocePetrovski** [comment]
Done. See v1.4
