### ISSUE TITLE
Remove Item bug

### ISSUE THREAD

**Issue by usamabinattique** [GocePetrovski/ScrollableSegmentedControl#22]
Currently if removeSegment is called, segmentView removes the segment at that index and shift it to the right index, but what if there are only two indexes (in my case) and upon removing 1st index it should fall back to 0th index but it crashes with the message "'attempt to scroll to invalid index path: <NSIndexPath: 0x60400003ec60> {length = 2, path = 0 - 1}'".  Please suggest a fix.

**Comment by GocePetrovski** [comment]
This is fixed in master and would be included in the next release.
