### ISSUE TITLE
change the image of selected segment

### ISSUE THREAD

**Issue by Emy87aa** [GocePetrovski/ScrollableSegmentedControl#3]
How can I Change the image of selected segment? Meaning that when I select a segment, its image change to a specific image and return to main when select other segment.

**Comment by GocePetrovski** [comment]
This functionality is not available in the current version.

**Comment by Emy87aa** [comment]
Could you add it for us, please? we need this functionality in our application. 
Thanks.

**Comment by GocePetrovski** [comment]
I will add it on my ToDo list.
Closing this down since it is not an issue but feature request.

**Comment by Emy87aa** [comment]
Good, waiting for this feature. Thanks.
