### ISSUE TITLE
I can't find any hint on this error.

### ISSUE THREAD

**Issue by beajco** [GocePetrovski/ScrollableSegmentedControl#38]
![Screen Shot 2019-04-26 at 1 50 36 PM](https://user-images.githubusercontent.com/38550296/56786110-5b3ab500-682a-11e9-9937-24b52347689d.png)

help please. ty

**Comment by GocePetrovski** [comment]
Put breakpoint at line 23, before stepping over, check if the `segmentedControl` is not `nil`.

**Comment by beajco** [comment]
![Screen Shot 2019-04-26 at 2 06 25 PM](https://user-images.githubusercontent.com/38550296/56786736-832b1800-682c-11e9-80e7-ab0cfbe2e874.png)

I tried on a new project..
That is the result sir.

**Comment by beajco** [comment]
I got it sir. The problem is i used segmented control and drag it to the controller and change it to 'ScrollableSegmentedControl'
From
@IBOutlet weak var segmentedControl : SegmentedControl!
To
@IBOutlet weak var segmentedControl : ScrollableSegmentedControl!
_______________________________________________________________________________________________
I solved it by, using UIView and changing the custom class to ScrollableSegmentedControl
