### ISSUE TITLE
swift 4?

### ISSUE THREAD

**Issue by jiqqaman** [GocePetrovski/ScrollableSegmentedControl#5]
Any chance you can update this to swift 4?

**Comment by hemangshah** [comment]
I believe, he will update it for Swift 4. As his recent commits are 8 days before so the developer is active. @GocePetrovski a new branch for Swift 4 can be helpful. What do you think?

**Comment by jiqqaman** [comment]
With some changes, I was able to get it running with iOS 11/Swift 4. Hopefully the PR is of any help. @hemangshah @GocePetrovski

**Comment by GocePetrovski** [comment]
Done in **swift4** branch. Will be merged into maser when Swift 4 is officially released.

**Comment by hemangshah** [comment]
@GocePetrovski, thanks for the quick update. One question, how to install Swift4 release via CocoaPods?

**Comment by jiqqaman** [comment]
@hemangshah 

`pod 'ScrollableSegmentedControl', :git => 'https://github.com/GocePetrovski/ScrollableSegmentedControl.git', :branch => 'swift4'`

**Comment by hemangshah** [comment]
@jiqqaman, thank you.
